title: Yixin Guo

author: Yixin Guo
avatar: /images/header.png
email: yixinguo@hkust-gz.edu.cn

collections:
  research:
    output: true
  people:
    output: true
    permalink: /people/:name/   # 关键：把 _people → /people/xxx/
